### ISSUE TITLE
Add support for Chrome 83

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-theme#139]
Related: https://developers.google.com/web/updates/2020/05/nic83#forms

- [x] What should a focused element look like? (Needs Design feedback)
- [ ] Add visual regression tests for focus states of buttons, inputs, etc.
- [ ] Need Design feedback about what a focused _and_ selected state should look like.
- [x] Address buttons that use `display: flex` (check: input group buttons, icon buttons, radio buttons, tab buttons, datepicker buttons).

[AB#1548550](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1548550)

**Comment by Blackbaud-AlexKingman** [comment]
Some examples of what our components look like on Chrome 88:

![Screen Shot 2020-05-29 at 3 45 34 PM](https://user-images.githubusercontent.com/18354182/83301260-554e9a80-a1c7-11ea-820a-eb9044ae4c44.png)
![Screen Shot 2020-05-29 at 3 46 10 PM](https://user-images.githubusercontent.com/18354182/83301265-57185e00-a1c7-11ea-9a8b-37027aa926d3.png)
![Screen Shot 2020-05-29 at 3 49 19 PM](https://user-images.githubusercontent.com/18354182/83301268-58498b00-a1c7-11ea-9b35-52c529ebd331.png)
![Screen Shot 2020-05-29 at 3 50 00 PM](https://user-images.githubusercontent.com/18354182/83301270-597ab800-a1c7-11ea-8399-d5a080010fd8.png)
![Screen Shot 2020-05-29 at 4 11 12 PM](https://user-images.githubusercontent.com/18354182/83301275-5b447b80-a1c7-11ea-87e3-00d4dcfcb77f.png)
![Screen Shot 2020-05-29 at 4 11 36 PM](https://user-images.githubusercontent.com/18354182/83301288-5ed80280-a1c7-11ea-9d32-c47e18d0162b.png)
![Screen Shot 2020-05-29 at 4 12 08 PM](https://user-images.githubusercontent.com/18354182/83301293-626b8980-a1c7-11ea-8ec1-b6d6b7fd2f9e.png)

**Comment by Blackbaud-AlexKingman** [comment]
Further reading on Google's recommended ways to have custom focus styles: https://web.dev/style-focus/
