### ISSUE TITLE
Datepicker box height and input/select box height mismatched

### ISSUE THREAD

**Issue by Blackbaud-DanGrochmal** [blackbaud/skyux-theme#152]
### Expected behavior

Datepicker box and input/select box are the same height

### Actual behavior

![image](https://user-images.githubusercontent.com/39523611/86599234-544e1d00-bf6c-11ea-8ecd-192d18ae9c12.png)
Datepicker is noticeably taller than other form boxes

[AB#1506796](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1506796)

**Comment by Blackbaud-AlexKingman** [comment]
The form inputs for modern theme are a work in progress. We will keep you updated as this work is completed.
