### ISSUE TITLE
Add CSS class for sky-btn-danger (variant of sky-btn-primary)

### ISSUE THREAD

**Issue by Blackbaud-VanesaiXiong** [blackbaud/skyux-theme#43]
### Expected behavior
CSS class to standardize the look/feel of destructive buttons, following the standards outlined [here](https://developer.blackbaud.com/skyux/design/styles/color).

### Actual behavior
No such CSS.

### Steps to reproduce

1. Create a button for a destructive action (such as deleting a record).
2. No CSS class(s), need to override sky-btn CSS to show destructive button.

### Severity
Cosmetic

### Impact
All skyux2 apps

**Comment by Blackbaud-AlexKingman** [comment]
Released in version 3.9.0.
