### ISSUE TITLE
Set background color of sky page

### ISSUE THREAD

**Issue by Blackbaud-AlexFortin** [blackbaud/skyux-theme#57]
### Expected behavior
Ability to set the background color for a SPA
### Actual behavior
You cannot set the background color of a SPA
### Steps to reproduce
Create any SKYUX SPA
### Impact
All skyux2 and skyux2 apps

**Comment by Blackbaud-SteveBrush** [comment]
This is possible using the `styles` property within **skyuxconfig.json**.
See: https://developer.blackbaud.com/skyux/learn/reference/configuration#app
