### ISSUE TITLE
update default page background

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-theme#64]
Per proposal from @Blackbaud-AdamFunderburk 

Default page bg should be white. Tile dashboards should still have the gray bg.

Related https://github.com/blackbaud/skyux-design-tokens/pull/25

**Comment by Blackbaud-ToddRoberts** [comment]
@Blackbaud-SteveBrush I merged that PR in design tokens, if we can do a release of that and then get the variable available here.

**Comment by Blackbaud-AdamFunderburk** [comment]
Here's a list of component changes that would be appropriate to make along with this update.

https://blackbaudinc.box.com/s/g6tzqganwrdtf50e0oi9vxczjuryqiff
