### ISSUE TITLE
Update Status indicator to change text wrap behavior

### ISSUE THREAD

**Issue by Blackbaud-AdamFunderburk** [blackbaud/skyux-theme#93]
Because Status indicator is implemented with `::before` there is an unintended consequence of text wrapping.
![image](https://user-images.githubusercontent.com/15896944/73860922-5029a200-480a-11ea-8ba7-3323bfd7b070.png)

Other components that give text fields their own container have superior wrapping behavior.
![image](https://user-images.githubusercontent.com/15896944/73861074-849d5e00-480a-11ea-9f68-b7271a747249.png)

Jagged left-aligning the text hurts readability, and the discrepancy in Status indicator's behavior creates inconsistency in our visual design language.

**Comment by Blackbaud-SteveBrush** [comment]
Fix was applied to the new status indicator component (see linked PR).
