### ISSUE TITLE
Evaluate exposing css classes for border mixins

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-theme#99]
Similar to how to we do margins, we've had a consumer ask if we could expose the border mixins as classes.

- https://developer.blackbaud.com/skyux/design/styles/borders
- https://developer.blackbaud.com/skyux/design/styles/spacing

**Comment by Blackbaud-SteveBrush** [comment]
Link to the border mixin: https://github.com/blackbaud/skyux-design-tokens/blob/master/src/scss/mixins.scss

**Let's expose CSS classes for:**
- border-bottom (all available colors)
- all 4 sides (light, dark)

**Comment by Blackbaud-BobbyEarl** [comment]
Added in [`3.1.0`](https://github.com/blackbaud/skyux-theme/blob/master/CHANGELOG.md#3100-2020-03-19) and documented with https://github.com/blackbaud/skyux2-docs/pull/873
